DemoPage:
  actAs:
    gjCompositionCanvas:  ~
  columns:
    title:                string(255)
    headline:             string(255)

###

DemoArticle:
  actAs:
    LooselyCoupled:
      ContentElement:     gjContentElement
  columns:
    title:                string(255)
    headline:             string(255)
    text:                 string(255)
    image:                string(36)

DemoImage:
  actAs:
    LooselyCoupled:
      ContentElement:     gjContentElement
  columns:
    title:                string(255)
    file:                 string(255)

